adminuser/urls.py
from django.contrib import admin
from django.urls import path
from .views import *


urlpatterns = [


    path('adminlogin/', adminlogin, name='adminlogin'),
    path('admindash/', admindash, name='admin_dash'),
    path('userregister/', register_user, name='userregister'),
    path('view_all_user/', view_all_users, name='view_all_users'),
    path('profilehome', profilehome, name='profilehome'),
    path('editprofile/', editprofile, name='editprofile'),
    path('user_logout/', user_logout, name='user_logout'),

    path('post/', PostListView.as_view(), name='post'),
    path('post/<int:pk>/', PostDetailView.as_view(), name='post-detail'),
    path('post/<int:pk>/update', PostUpdateView.as_view(), name='post-update'),
    path('create_post/', create_post, name='create_post'),
    path('post/<int:pk>/delete', PostDeleteView.as_view(), name='post-delete'),

    path('author/<str:username>/', author_profile, name='author-profile'),

    path('posts/<int:year>/<int:month>/<int:day>/', posts_by_date, name='posts-by-date'),

   ]

pwe/urls.py
from django.contrib import admin
from django.urls import path,include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('Main.urls')),


    path('adminuser/',include('adminuser.urls')),
    path('room/',include('room.urls')),

]+ static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

Main/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=120)
    email = models.EmailField()
    address = models.TextField()
    message = models.TextField()

    def __str__(self):
        return self.name

from django.contrib.auth.models import User

class Leave(models.Model):
    """
    Model to store information about leave requests.
    """
    # Model fields
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    contact_number = models.CharField(max_length=15)
    reason = models.TextField()
    room_number = models.CharField(max_length=50)
    bed_number = models.CharField(max_length=50)
    start_date = models.DateField()
    end_date = models.DateField()


    # Define choices for status field
    STATUS_CHOICES = [
        ('pending', 'Pending'),
        ('approved', 'Approved'),
        ('denied', 'Denied'),
    ]

    # Status field using choices
    status = models.CharField(max_length=10, choices=STATUS_CHOICES, default='pending')
    DUE_CHOICES = [
        ('yes', 'Yes'),
        ('no', 'No'),
    ]
    due = models.CharField(max_length=3, choices=DUE_CHOICES, default='no')

    def __str__(self):
        return f"Leave Request by {self.user.username}"

adminuser/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from PIL import Image
from django.urls import reverse

class Profile(models.Model):
    PROF_CHOICES = [
        ('Student', 'Student'),
        ('Job', 'Job'),
        ('Other', 'Other'),
    ]

    WORK_LOC_CHOICES = [
        ('College', 'College'),
        ('Coaching', 'Coaching'),
        ('Office', 'Office'),
        ('Other', 'Other'),
    ]


        # Other fields...

    user = models.OneToOneField(User, on_delete=models.CASCADE)
    name = models.CharField( max_length=200, null=True)
    profile_img = models.ImageField(default='image/defalut.jpg',upload_to='media')
    address = models.CharField(max_length=250)
    profession = models.CharField(max_length=100, choices=PROF_CHOICES)
    assosiat_with = models.CharField(max_length=250, blank=True, null=True, choices=WORK_LOC_CHOICES)
    college_name = models.CharField(max_length=250, blank=True, null=True)
    coaching_name = models.CharField(max_length=250, blank=True, null=True)
    office_name = models.CharField(max_length=250, blank=True, null=True)
    other = models.CharField(max_length=250, blank=True, null=True)
    photo = models.ImageField(upload_to='photos/', blank=True, null=True)
    adhar_card = models.ImageField(upload_to='adhar_card/', blank=True, null=True)
    phone_number = models.CharField(max_length=15)
    father_contact_number = models.CharField(max_length=15, blank=True, null=True)
    date_of_birth = models.DateField(null=True, blank=True)
    date_of_joing = models.DateField(null=True, blank=True)

    def __str__(self):
        return f"{self.user.username}'s profile"


class Post(models.Model):
    title = models.CharField(max_length=100)
    description = models.TextField()
    date_posted = models.DateTimeField(default=timezone.now)
    author = models.ForeignKey(User, on_delete=models.CASCADE)
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-detail', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.image:
            img = Image.open(self.image.path)

            # Define your maximum image size here
            max_width = 400
            max_height = 200

            if img.width > max_width or img.height > max_height:
                output_size = (max_width, max_height)
                img.thumbnail(output_size)
                img.save(self.image.path)

adminuser/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django import forms
from django.forms.models import ModelForm
from django.forms.widgets import FileInput
from .models import *


class CreateUserForm(UserCreationForm):
    class Meta:
        model =User
        fields = ['username','email','password1' ,'password2']

class ProfileForm(ModelForm):
    class Meta:
        model = Profile
        fields = '__all__'
        exclude = ['user']
        widgets ={
            'profile_img': FileInput(),
        }
class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ['title', 'description', 'image']  # Assuming 'title', 'content', and 'image' are fields in your Post model

        widgets = {
            'title': forms.TextInput(attrs={'class': 'form-control'}),
            'description': forms.Textarea(attrs={'class': 'form-control', 'rows': 5}),
            'image': forms.ClearableFileInput(attrs={'class': 'form-control-file'}),
        }

adminuser/views.py
from django.shortcuts import render,redirect
from django.contrib import messages
from django.contrib.auth import authenticate,login,logout
from django.views.generic import  DetailView, UpdateView, DeleteView,ListView
from .forms import *
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from datetime import datetime



class PostListView(ListView):
    model = Post
    template_name = 'post.html'
    context_object_name = 'posts'
    ordering = ['-date_posted']


class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'




class PostDetailView(DetailView):
    model = Post
    template_name = 'post_detail.html'



class PostUpdateView(LoginRequiredMixin, UpdateView):
    model = Post
    form_class = PostForm  # Use the customized form
    template_name = 'create_post.html'

    def form_valid(self, form):
        form.instance.author = self.request.user
        return super().form_valid(form)


class PostDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Post
    success_url = '/'
    template_name = 'post_confirm_delete.html'

    def test_func(self):
        post = self.get_object()
        if self.request.user == post.author:
            return True
        return False


def create_post(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            # Save the form data to the database
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('post')  # Redirect to the user's profile page
    else:
        form = PostForm()
    return render(request, 'create_post.html', {'form': form})



def adminlogin(request):
    if request.method == 'POST':
        adminname = request.POST.get('adminname')
        adminpassword = request.POST.get('adminpassword')

        user = authenticate(request, username=adminname,password= adminpassword)

        if user  and user.is_superuser:

            login(request,user)
            return redirect('post')

        else:

             error_message = 'Invalid username or password. Only superusers can log in.'
             return render(request,'adminlogin.html',{'error_message':error_message})


    return render(request,'adminlogin.html')

def admindash(request):
    return render(request, 'admindash.html')


def register_user(request):
    form = CreateUserForm()

    if request.method == 'POST':
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
            messages.info(request, 'Account is created.')
            return redirect('user_login')
        else:
            context = {'form': form}
            messages.info(request, 'Invalid credentials')
            return render(request, 'register_page.html', context)

    context = {'form': form}
    return render(request, 'register_page.html', context)

def view_all_users(request):
   users = User.objects.all()
   return render(request,'view_all_users.html',{'users':users})





@login_required
def profilehome(request):
    user = request.user
    return render(request, 'profilehome.html', {'user': user})


@login_required(login_url='user_login')
def editprofile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        if form.is_valid():
            form.save()
            username = request.user.username
            messages.success(request, f'{username}, Your profile is updated.')
            return redirect('profilehome')
    else:
        form = ProfileForm(instance=request.user.profile)
    context = {'form': form}
    return render(request, 'editprofile.html', context)

def user_logout(request):
    logout(request)
    return redirect('user_login')

from django.shortcuts import render
from django.contrib.auth.models import User

def author_profile(request, username):
    # Get the user object based on username
    user = User.objects.get(username=username)
    # Get all posts by this user
    posts = user.post_set.all()
    # Render the author profile template with user and posts
    return render(request, 'author_profile.html', {'user': user, 'posts': posts})


def posts_by_date(request, year, month, day):
    # Convert year, month, day to datetime object
    date_obj = datetime(year, month, day)

    # Filter posts for the given date
    posts = Post.objects.filter(date_posted__year=year, date_posted__month=month, date_posted__day=day)

    # Render template with posts and date
    return render(request, 'datewisepost.html', {'date': date_obj, 'posts': posts})

adminuser/templates/admindash.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Admin-login{% endblock title %}
{% block content %}



{% endblock %}

adminuser/templates/adminlogin.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Admin-login{% endblock title %}
{% block style %}
 
<style>

    .login-container {
        width: 350px;
        margin: 0 auto;
        padding: 40px;
        padding-bottom: 30px; /* Reduced bottom padding */
        background-color: #f9f9f9;
        border-radius: 10px;
        box-shadow: 0 0 20px rgba(0, 0, 0, 0.1); /* Add a subtle shadow effect */
    }
    

    .login-container h2 {
        margin-bottom: 20px;
        color: #333;
        text-align: center;
        font-size: 24px;
    }
    
   
    .login-container label {
        display: block;
        margin-bottom: 10px;
        color: #555;
    }
    
   
    .login-container input[type="text"],
    .login-container input[type="password"] {
        width: 100%;
        padding: 12px;
        margin-bottom: 20px;
        border: 1px solid #ccc;
        border-radius: 6px;
        font-size: 16px;
        transition: border-color 0.3s ease;
    }
    
   
    .login-container input[type="text"]:focus,
    .login-container input[type="password"]:focus {
        border-color: #007bff;
    }
    

    .login-container button[type="submit"] {
        width: 100%;
        padding: 14px;
        background-color: #AA336A;
        color: #fff;
        border: none;
        border-radius: 6px;
        cursor: pointer;
        font-size: 16px;
        transition: background-color 0.3s ease;
    }
    
    .login-container button[type="submit"]:hover {
        background-color: #AA336A;
    }
    
    .error-message {
        color: #f33;
        text-align: center;
        margin-top: 10px;
    }
    
        </style>
{% endblock %}
{% block content %}


    {% if error_message %}
        <p class="error-message">{{ error_message }}</p>
    {% endif %}
    <div class="login-container">
        <h2>Login</h2>
        <form action="" method="POST">
            {% csrf_token %}
            <label for="adminname">Username:</label>
            <input type="text" name="adminname" id="adminname" placeholder="Username"><br>
            <label for="adminpassword">Password:</label>
            <input type="password" name="adminpassword" id="adminpassword" placeholder="Password"><br>
            <button type="submit">Log in</button><br>

        </form>
    </div>
{% endblock %}

adminuser/templates/author_profile.html
{% extends 'base.html' %}

{% block content %}

<main class="main-container">
    <div class="container">


        <div class="user-content-container">
            <p class="name"><b>Name: </b>{{ user.profile.name }}</p>
            <p class="address"><b>Address: </b>{{ user.profile.address }}</p>


        </div>

    </div>
</main>

<div class="container">
    {% for post in posts %}
    <!-- All posts have the same class "post" -->
    <div  class="post"  style="margin-bottom: 40px;">
        <article class="media content-section">

            <div class="media-body">
                <div class="article-metadata">
                    <!-- Wrap author's name with anchor tag -->
                    <h4 class="mr-2"><p>{{ post.author }}</p></h4>
                    <h5 class="text-muted">{{ post.date_posted|date:"F d, Y" }}</h5><hr>
                    <h3><a style="color:black " class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h3>
                </div>
                {% if post.image %}
                <img class="article-image fixed-size-image" src="{{ post.image.url }}" alt="{{ post.title }}">
                {% endif %}
            </div>
        </article>
    </div>
    {% endfor %}
</div>
{% endblock %}

adminuser/templates/create_post.html
{% extends "base.html" %}
{% block content %}
<style>
    form {
    margin: 20px auto;
    padding: 20px;
    max-width: 500px;
     border-radius: 5px;

}

h2 {
    text-align: center;
    margin-bottom: 20px;
}

label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
}

input[type="text"],
textarea,
button,
input[type="file"] {
    width: 100%;
    padding: 10px;
    margin-bottom: 15px;
   border-radius: 5px;

    box-sizing: border-box;
}

textarea {
    resize: vertical;
}

button {
    background-color: #AA336A;
    color: white;
    border: none;
    cursor: pointer;
    width:20%;
}


</style>
<div class="container">
    <h2>Create a New Post</h2>
    <form method="post" enctype="multipart/form-data" class="post-form">
        {% csrf_token %}
        <div class="form-group">
            <label for="id_title">Title:</label>
            {{ form.title }}
        </div>
        <div class="form-group">
            <label for="id_description">Description:</label>
            {{ form.description }}
        </div>
        <div class="form-group">
            <label for="id_image">Image:</label>
            {{ form.image }}
        </div>
        <button type="submit" >Submit</button>
    </form>
</div>
{% endblock %}

adminuser/templates/datewisepost.html
{% extends "base.html" %}
{% block content %}
    <h1>Posts uploaded on {{ date }}</h1>
    {% for post in posts %}
        <article class="media content-section">

            <div class="media-body">
                <div class="article-metadata">
                    <p class="mr-2">{{ post.author }}</p>
                    <small class="text-muted">{{ post.date_posted|date:"F d, Y" }}</small>
                </div>
                <h3><a class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h3>
                {% if post.image %}
                    <img class="article-image fixed-size-image" src="{{ post.image.url }}" alt="{{ post.title }}" onclick="openImageModal('{{ post.image.url }}', '{{ post.title }}')">
                {% endif %}
            </div>
        </article>
    {% endfor %}
{% endblock %}

adminuser/templates/editprofile.html
{% extends 'base.html' %}
{% block title %} Profile{% endblock %}

{% block content %}
<style>

.main-container {
    width: 60%;
    background-color: white;
    margin: 10% auto;
    border-radius: 2em;
    padding: 2em 2em;

}

.container {
    display: flex;
    margin: 2em 2em;
    align-items: center;
    justify-content: space-between;
      flex-direction: column;
}


#id_profile_img {
    width: 70% - 1.6em;
    padding: .8em .8em;
    margin-top: 1.5em;
    width: 60%;
    padding: .8em;
    background-color: #AA336A;;
    border: none;
    border-radius: 3px;
    font-size: 1em;
    font-weight: 600;
    cursor: pointer;
}


.user-profile-form-container {
    width: 60%;
    margin: 2em;
    padding: 0;
}

.user-content-container ul{
    list-style-type: none;
    display: flex;
    flex-direction: column;
    width: 100%;
    justify-content: center;

}

.user-content-container ul  li {
    display: flex;
    flex-direction: column;
    width: 100%;
}



.user-profile-form-container label {
    font-size: larger;
    width: 100%;
    margin: .5em auto .3em 0;
}

.user-profile-form-container input {
    width: 100%-14px;
    height: 2.5em;
    border-radius: 3px;
    border: solid #707070 1px;
    margin: .1em 0;
    padding: 0 7px;
}

.profile-save-button {
    margin-top: 1.5em;
    width: 40%;
    padding: .8em;
    background-color: #AA336A;
    border: none;
    border-radius: 5px;
    font-size: 1em;
    font-weight: 600;
    cursor: pointer;
    color:white;
}


@media only screen and (max-width: 1200px) {
    .container {
        display: block;
        margin-left: .1em;
        margin-right: .1em;
    }

    .profile-photo-container {
        width: 100%;
    }
  }


.notification-container {
    width: 100%;
    display: flex;
    justify-content: center;
}
.notification {
    padding: .8em 5%;
    background-color: rgba(64, 243, 243, 0.808);
    display: flex;
    align-items: center;
    justify-content: space-between;
    width: 60%;
    border-radius: 5px;
}




.profile-photo-container {

    display: flex;
    flex-direction: column;
    justify-content: center;
    align-items: center;
}

.profile-photo-container img {
    width: 10em;
    height: 10em;
    object-fit: cover;
    border-radius: 50%;
    margin: .7em auto;
}
.profile-page-heading {
    font-size: 20px; /* Font size */
    font-weight: bold; /* Bold font weight */
    text-align: center; /* Center align text */
    margin-bottom: 20px; /* Bottom margin */
    color: dark; /* Text color */
      flex-direction: column;
}





</style>



<main class="main-container">
    <form class="container" action="" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="profile-photo-container profile-photo-form-container">
            <p class="profile-page-heading">Edit your profile</p>
            <img src="{{ user.profile.profile_img.url }}" alt="user-image" width="" srcset="">
            {{ form.profile_img }}
        </div>

        <div class="user-content-container user-profile-form-container">
            <ul>
                <li class="name">
                    <label for="id_name">Your Name</label>
                    {{ form.name.errors }}
                    {{ form.name }}
                </li>
                <li class="address">
                    <label for="id_address">Address</label>
                    {{ form.address.errors }}
                    {{ form.address }}
                </li>
                <li class="profession">
                    <label for="id_profession">Profession</label>
                    {{ form.profession.errors }}
                    {{ form.profession }}
                </li>
                <li class="associated-with">
                    <label for="id_assosiat_with">Associated with</label>
                    {{ form.assosiat_with.errors }}
                    {{ form.assosiat_with }}
                </li>
                <li class="college-name">
                    <label for="id_college_name">College Name</label>
                    {{ form.college_name.errors }}
                    {{ form.college_name }}
                </li>
                <li class="coaching-name">
                    <label for="id_coaching_name">Coaching Name</label>
                    {{ form.coaching_name.errors }}
                    {{ form.coaching_name }}
                </li>
                <li class="office-name">
                    <label for="id_office_name">Office Name</label>
                    {{ form.office_name.errors }}
                    {{ form.office_name }}
                </li>
                <li class="other">
                    <label for="id_other">Other</label>
                    {{ form.other.errors }}
                    {{ form.other }}
                </li>
                <li class="photo">
                    <label for="id_photo">Photo</label>
                    {{ form.photo.errors }}
                    {{ form.photo }}
                </li>
                <li class="adhar-card">
                    <label for="id_adhar_card">Adhar Card</label>
                    {{ form.adhar_card.errors }}
                    {{ form.adhar_card }}
                </li>
                <li class="phone-number">
                    <label for="id_phone_number">Phone Number</label>
                    {{ form.phone_number.errors }}
                    {{ form.phone_number }}
                </li>
                <li class="father-contact-number">
                    <label for="id_father_contact_number">Father's Contact Number</label>
                    {{ form.father_contact_number.errors }}
                    {{ form.father_contact_number }}
                </li>
                <li class="date-of-birth">
                    <label for="id_date_of_birth">Date of Birth</label>
                    {{ form.date_of_birth.errors }}
                    {{ form.date_of_birth }}
                </li>
                <li class="date-of-joining">
                    <label for="id_date_of_joing">Date of Joining</label>
                    {{ form.date_of_joing.errors }}
                    {{ form.date_of_joing }}
                </li>
            </ul>
            <button type="submit" class="profile-save-button">Save</button>
        </div>
    </form>
</main>

<script>
    var id_name = document.getElementById('id_name');
    var id_address = document.getElementById('id_address');
    var id_profession = document.getElementById('id_profession');
    id_name.placeholder = 'Your Name';
    id_address.placeholder = 'Address';
    id_profession.placeholder = 'Profession';
</script>
    <!-- Your home page content goes here -->
{% endblock %}

adminuser/templates/post.html
{% extends 'base.html' %}
{% block style %}
 
<style>
   
    .article-image {
        max-width: 100%; 
        height: auto; 
        width: 300px;
        margin-top: 10px; 
    }
    
        .post {
            margin-bottom: 20px; 
            margin-top: 5px;
            padding: 10px;
            border-radius: 5px;
            background-color: #f8f9fa;
            width: 60%;
            margin: auto;
        }
    
        .article-metadata {
            margin-bottom: 5px;
        }
    
        .article-title {
            text-decoration: none;
            color: black;
        }
    
        .article-title:hover {
            text-decoration: underline;
        }
    
       
        .full-size-image {
            width: 50%; 
            height: auto;
            margin-top: 10px;
        }
    </style>
    
{% endblock %}
{% block content %}
<div class="container">
    {% for post in posts %}
    <!-- All posts have the same class "post" -->
    <div  class="post"  style="margin-bottom: 40px;">
        <article class="media content-section">
            <img class="rounded-circle article-img" src="{% if post.author.profile.image %}{{ post.author.profile.image.url }}{% endif %}">
            <div class="media-body">
                <div class="article-metadata">
                    <!-- Wrap author's name with anchor tag -->
                    <h4 class="mr-2"><a href="{% url 'author-profile' post.author.username %}">{{ post.author }}</a></h4>
                    <!-- Date link -->
                    <h5 class="text-muted"><a href="{% url 'posts-by-date' post.date_posted|date:'Y' post.date_posted|date:'m' post.date_posted|date:'d' %}">{{ post.date_posted|date:"F d, Y" }}</a></h5><hr>
                    <h3><a style="color:black " class="article-title" href="{% url 'post-detail' post.id %}">{{ post.title }}</a></h3>
                </div>
                {% if post.image %}
                <!-- Wrap image with anchor tag linking to full-size image -->
                <a href="{{ post.image.url }}" target="_blank">
                    <img class="article-image fixed-size-image full-size-image" src="{{ post.image.url }}" alt="{{ post.title }}">
                </a>
                {% endif %}
            </div>
        </article>
    </div>
    {% endfor %}
</div>

{% endblock %}

adminuser/templates/post_confirm_delete.html
{% extends "base.html" %}
{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Post</legend>
                <h2>Are you sure you want to delete the post "{{ object.title }}"</h2>
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'post-detail' object.pk %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock %}

adminuser/templates/register_page.html
{% extends "base.html" %}
{% load static %}
{% block style %}
 
<style>
    
    * {
        margin: 0;
        padding: 0;
        box-sizing: border-box;
    }
    
    
    
    .container {
        max-width: 600px;
        margin: 0 auto;
        padding: 20px;
    }
    
    .signup-heading {
        text-align: center;
        margin-bottom: 20px;
    }
    
    .user-content-container {
        background-color: #fff;
        border-radius: 8px;
        padding: 20px;
    }
    
    .user-content-container form ul {
        list-style-type: none;
        padding: 0;
    }
    
    .user-content-container form ul li {
        margin-bottom: 15px;
    }
    
    .user-content-container form ul li label {
        font-weight: bold;
        display: block;
    }
    
    .user-content-container form ul li input[type="text"],
    .user-content-container form ul li input[type="email"],
    .user-content-container form ul li input[type="password"] {
        width: 100%;
        padding: 10px;
        border: 1px solid #ccc;
        border-radius: 5px;
        transition: border-color 0.3s ease;
    }
    
    .user-content-container form ul li input[type="text"]:focus,
    .user-content-container form ul li input[type="email"]:focus,
    .user-content-container form ul li input[type="password"]:focus {
        border-color: #007bff;
    }
    
    .signup-button {
        background-color: #AA336A;
        color: #fff;
        border: none;
        padding: 10px 20px;
        border-radius: 5px;
        cursor: pointer;
        transition: background-color 0.3s ease;
    }
    
    .signup-button:hover {
        background-color:  #AA336A;
    }
    
    .login-link {
        text-align: center;
        margin-top: 20px;
    }
    
    .login-link a {
        color: #AA336A;
        text-decoration: none;
    }
    
    .login-link a:hover {
        text-decoration: underline;
    }
    
    .notification-container {
        position: fixed;
        top: 20px;
        left: 50%;
        transform: translateX(-50%);
        z-index: 9999;
    }
    
    .notification {
        background-color: #007bff;
        color: #fff;
        padding: 10px 20px;
        border-radius: 5px;
        display: flex;
        align-items: center;
    }
    
    .notification p {
        margin: 0;
        margin-right: 10px;
    }
    
    #cross {
        cursor: pointer;
    }
    
    </style>
{% endblock %}
{% block content %}




<main class="main-container">
    <div class="container">
        <h2 class="signup-heading">Sign Up</h1>
        <div class="user-content-container user-profile-form-container">
            <form action="" method="POST">
                {% csrf_token %}
                <ul>
                    <li class="name">
                        <label for="id_username">Username</label>
                        {{ form.username.errors }}
                        {{ form.username }}
                    </li>
                    <li class="email">
                        <label for="id_email">Email</label>
                        {{ form.email.errors }}
                        {{ form.email }}
                    </li>
                    <li class="pass">
                        <label for="id_password1">Password</label>
                        {{ form.password1.errors }}
                        {{ form.password1 }}
                    </li>
                    <li class="confirm-pass">
                        <label for="id_password2">Confirm Password</label>
                        {{ form.password2.errors }}
                        {{ form.password2 }}
                    </li>
                </ul>
                <button class="signup-button" type="submit">Sign up</button>
                <p class="login-link">Have an account? <a href="{% url 'user_login' %}">Log in</a></p>
            </form>
        </div>
    </div>
</main>

<script>
    var id_username = document.getElementById('id_username');
    var id_email = document.getElementById('id_email');
    var id_password1 = document.getElementById('id_password1');
    var id_password2 = document.getElementById('id_password2');

    id_username.placeholder = 'Username';
    id_email.placeholder = 'Email';
    id_password1.placeholder = 'Password';
    id_password2.placeholder = 'Confirm password';
</script>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.min.js" integrity="undefined" crossorigin="anonymous"></script>
{% endblock %}

adminuser/templates/view_rooms.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>